/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Caixa de entrada de alertas (RF12)
         * @description Somente os alertas do usuário autenticado, mais recentes primeiro.
         */
        get: operations["alerts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha um alerta
         * @description Leitura + duas transições. Alertas nascem do job, nunca de um POST.
         */
        get: operations["alerts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}/dismiss/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Descarta o alerta
         * @description Sai da caixa de entrada sem apagar o histórico.
         */
        post: operations["alerts_dismiss_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marca como lido
         * @description Leitura + duas transições. Alertas nascem do job, nunca de um POST.
         */
        post: operations["alerts_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login (RF02)
         * @description Retorna o access token no corpo e grava o refresh token em cookie httpOnly. Apos 5 falhas na combinacao IP+usuario, django-axes responde 429.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout (RF02)
         * @description Coloca o refresh token na blacklist e apaga o cookie. Idempotente: token já inválido também resulta em 204.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados da conta autenticada */
        get: operations["auth_me_retrieve"];
        /** Dados da conta autenticada */
        put: operations["auth_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Dados da conta autenticada */
        patch: operations["auth_me_partial_update"];
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renova o access token
         * @description Lê o refresh do cookie httpOnly (ou do corpo). Com rotação ativa, o token antigo vai para a blacklist e um novo é gravado no cookie.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cadastro de usuário (RF01) */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Retorna 200 se a aplicação alcança o banco; 503 caso contrário.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as tabelas da conta (RF04) */
        get: operations["tables_list"];
        put?: never;
        /** Cria uma tabela (RF03) */
        post: operations["tables_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalha uma tabela com suas colunas */
        get: operations["tables_retrieve"];
        /** Substitui uma tabela */
        put: operations["tables_update"];
        post?: never;
        /** Exclui uma tabela e tudo dentro dela */
        delete: operations["tables_destroy"];
        options?: never;
        head?: never;
        /** Atualiza uma tabela */
        patch: operations["tables_partial_update"];
        trace?: never;
    };
    "/api/tables/{table_id}/alert-rules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regras de alerta da tabela */
        get: operations["tables_alert_rules_list"];
        put?: never;
        /** Cria uma regra de antecedência */
        post: operations["tables_alert_rules_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_id}/alert-rules/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalha uma regra */
        get: operations["tables_alert_rules_retrieve"];
        /** Substitui uma regra */
        put: operations["tables_alert_rules_update"];
        post?: never;
        /** Remove uma regra */
        delete: operations["tables_alert_rules_destroy"];
        options?: never;
        head?: never;
        /** Atualiza uma regra */
        patch: operations["tables_alert_rules_partial_update"];
        trace?: never;
    };
    "/api/tables/{table_id}/columns/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as colunas da tabela (RF05) */
        get: operations["tables_columns_list"];
        put?: never;
        /** Adiciona uma coluna (RF05, RF06) */
        post: operations["tables_columns_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_id}/columns/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalha uma coluna */
        get: operations["tables_columns_retrieve"];
        /** Substitui uma coluna */
        put: operations["tables_columns_update"];
        post?: never;
        /** Remove uma coluna */
        delete: operations["tables_columns_destroy"];
        options?: never;
        head?: never;
        /** Renomeia ou reconfigura uma coluna */
        patch: operations["tables_columns_partial_update"];
        trace?: never;
    };
    "/api/tables/{table_id}/columns/reorder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reordena as colunas da tabela
         * @description Recebe os ids de todas as colunas na ordem desejada e reatribui as posições numa única transação. A constraint de posição é DEFERRABLE, então os estados intermediários duplicados não quebram nada.
         */
        patch: operations["tables_columns_reorder_partial_update"];
        trace?: never;
    };
    "/api/tables/{table_id}/records/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os registros da tabela (RF10, RF11) */
        get: operations["tables_records_list"];
        put?: never;
        /** Insere um registro (RF07) */
        post: operations["tables_records_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_id}/records/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalha um registro */
        get: operations["tables_records_retrieve"];
        /** Substitui um registro (RF08) */
        put: operations["tables_records_update"];
        post?: never;
        /** Exclui um registro (RF09) */
        delete: operations["tables_records_destroy"];
        options?: never;
        head?: never;
        /** Atualiza um registro (RF08) */
        patch: operations["tables_records_partial_update"];
        trace?: never;
    };
    "/api/tables/{table_id}/records/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exporta a tabela em CSV (RF13)
         * @description Exporta exatamente o que a listagem devolveria: os mesmos filtros (`?status=`, `?due_before=`…) e a mesma ordenação valem aqui. Colunas na ordem definida na tabela, com os rótulos como cabeçalho.
         */
        get: operations["tables_records_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Corpo de /auth/refresh/. O refresh rotacionado sai só no cookie. */
        AccessToken: {
            readonly access: string;
        };
        /**
         * @description Payload da notificação.
         *
         *     RS05 — carrega o mínimo: nome da tabela, vencimento e um rótulo curto do
         *     registro. NUNCA o `data` completo, e nunca o valor de uma coluna marcada
         *     como sensível. Uma notificação é a superfície mais exposta do sistema:
         *     aparece em lista, vira e-mail e acaba em log.
         */
        Alert: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly table_id: string;
            readonly table_name: string;
            /** Format: uuid */
            readonly record_id: string;
            readonly label: string;
            /**
             * Data de disparo
             * Format: date
             */
            readonly trigger_date: string;
            /** Format: date */
            readonly due_date: string;
            /** Situação */
            readonly status: components["schemas"]["StatusEnum"];
            readonly is_stale: boolean;
            /**
             * Notificado em
             * Format: date-time
             */
            readonly notified_at: string | null;
            /**
             * Lido em
             * Format: date-time
             */
            readonly read_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        AlertRule: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Dias de antecedência
             * @description 3 = avisa 3 dias antes · 0 = no dia · -1 = 1 dia depois (cobrança de atraso).
             */
            offset_days: number;
            /** Canal */
            channel?: components["schemas"]["ChannelEnum"];
            /** Ativa */
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `in_app` - No aplicativo
         *     * `email` - E-mail
         * @enum {string}
         */
        ChannelEnum: "in_app" | "email";
        Column: {
            /** Format: uuid */
            readonly id: string;
            /** Chave */
            readonly key: string;
            /** Rótulo */
            name: string;
            /** Tipo */
            type: components["schemas"]["TypeEnum"];
            /** Posição */
            readonly position: number;
            /** Obrigatória */
            is_required?: boolean;
            /** Sensível */
            is_sensitive?: boolean;
            /** Opções */
            options?: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Adiciona o usuário ao corpo da resposta de login. */
        Login: {
            email: string;
            password: string;
        };
        PaginatedAlertList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Alert"][];
        };
        PaginatedAlertRuleList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AlertRule"][];
        };
        PaginatedColumnList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Column"][];
        };
        PaginatedRecordList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Record"][];
        };
        PaginatedTableList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Table"][];
        };
        PatchedAlertRule: {
            /** Format: uuid */
            readonly id?: string;
            /**
             * Dias de antecedência
             * @description 3 = avisa 3 dias antes · 0 = no dia · -1 = 1 dia depois (cobrança de atraso).
             */
            offset_days?: number;
            /** Canal */
            channel?: components["schemas"]["ChannelEnum"];
            /** Ativa */
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedColumn: {
            /** Format: uuid */
            readonly id?: string;
            /** Chave */
            readonly key?: string;
            /** Rótulo */
            name?: string;
            /** Tipo */
            type?: components["schemas"]["TypeEnum"];
            /** Posição */
            readonly position?: number;
            /** Obrigatória */
            is_required?: boolean;
            /** Sensível */
            is_sensitive?: boolean;
            /** Opções */
            options?: unknown;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedRecord: {
            /** Format: uuid */
            readonly id?: string;
            /** Valores */
            data?: unknown;
            /**
             * Vencimento
             * Format: date
             */
            readonly due_date?: string | null;
            /** @description Um de: overdue, due_today, due_soon, on_track, no_due */
            readonly due_status?: string;
            /** @description Negativo quando já venceu; null quando não há vencimento. */
            readonly days_until_due?: number | null;
            /** Posição manual */
            position?: number | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedReorder: {
            /** @description Ids de TODAS as colunas da tabela, na ordem desejada. */
            order?: string[];
        };
        PatchedTable: {
            /** Format: uuid */
            readonly id?: string;
            /** Nome */
            name?: string;
            /** Descrição */
            description?: string;
            /** Dias de antecedência do alerta */
            alert_lead_days?: number;
            readonly columns?: components["schemas"]["Column"][];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Representação pública do usuário. Nunca inclui `password`. */
        PatchedUser: {
            /** Format: uuid */
            readonly id?: string;
            /**
             * E-mail
             * Format: email
             */
            readonly email?: string;
            /** Nome */
            name?: string;
            /** Fuso horário */
            timezone?: string;
            /** Format: date-time */
            readonly created_at?: string;
        };
        Record: {
            /** Format: uuid */
            readonly id: string;
            /** Valores */
            data?: unknown;
            /**
             * Vencimento
             * Format: date
             */
            readonly due_date: string | null;
            /** @description Um de: overdue, due_today, due_soon, on_track, no_due */
            readonly due_status: string;
            /** @description Negativo quando já venceu; null quando não há vencimento. */
            readonly days_until_due: number | null;
            /** Posição manual */
            position?: number | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Register: {
            /** Format: uuid */
            readonly id: string;
            /**
             * E-mail
             * Format: email
             */
            email: string;
            /** Nome */
            name?: string;
            /** Fuso horário */
            timezone?: string;
            password: string;
        };
        /**
         * @description * `pending` - Pendente
         *     * `sent` - Enviado
         *     * `read` - Lido
         *     * `dismissed` - Descartado
         *     * `failed` - Falhou
         * @enum {string}
         */
        StatusEnum: "pending" | "sent" | "read" | "dismissed" | "failed";
        Table: {
            /** Format: uuid */
            readonly id: string;
            /** Nome */
            name: string;
            /** Descrição */
            description?: string;
            /** Dias de antecedência do alerta */
            alert_lead_days?: number;
            readonly columns: components["schemas"]["Column"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `text` - Texto
         *     * `number` - Número
         *     * `date` - Data
         *     * `datetime` - Data e hora
         *     * `boolean` - Booleano
         *     * `email` - E-mail
         *     * `select` - Lista de opções
         *     * `due_date` - Data de vencimento
         * @enum {string}
         */
        TypeEnum: "text" | "number" | "date" | "datetime" | "boolean" | "email" | "select" | "due_date";
        /** @description Representação pública do usuário. Nunca inclui `password`. */
        User: {
            /** Format: uuid */
            readonly id: string;
            /**
             * E-mail
             * Format: email
             */
            readonly email: string;
            /** Nome */
            name?: string;
            /** Fuso horário */
            timezone?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alerts_list: {
        parameters: {
            query?: {
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /**
                 * @description * `pending` - Pendente
                 *     * `sent` - Enviado
                 *     * `read` - Lido
                 *     * `dismissed` - Descartado
                 *     * `failed` - Falhou
                 */
                status?: "dismissed" | "failed" | "pending" | "read" | "sent";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAlertList"];
                };
            };
        };
    };
    alerts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este alerta. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    alerts_dismiss_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este alerta. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    alerts_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este alerta. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Login"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tables_list: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTableList"];
                };
            };
        };
    };
    tables_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Table"];
                "application/x-www-form-urlencoded": components["schemas"]["Table"];
                "multipart/form-data": components["schemas"]["Table"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Table"];
                };
            };
        };
    };
    tables_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este tabela. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Table"];
                };
            };
        };
    };
    tables_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este tabela. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Table"];
                "application/x-www-form-urlencoded": components["schemas"]["Table"];
                "multipart/form-data": components["schemas"]["Table"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Table"];
                };
            };
        };
    };
    tables_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este tabela. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tables_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este tabela. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTable"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTable"];
                "multipart/form-data": components["schemas"]["PatchedTable"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Table"];
                };
            };
        };
    };
    tables_alert_rules_list: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
            };
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAlertRuleList"];
                };
            };
        };
    };
    tables_alert_rules_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRule"];
                "application/x-www-form-urlencoded": components["schemas"]["AlertRule"];
                "multipart/form-data": components["schemas"]["AlertRule"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
        };
    };
    tables_alert_rules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este regra de alerta. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
        };
    };
    tables_alert_rules_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este regra de alerta. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRule"];
                "application/x-www-form-urlencoded": components["schemas"]["AlertRule"];
                "multipart/form-data": components["schemas"]["AlertRule"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
        };
    };
    tables_alert_rules_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este regra de alerta. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regra removida com os alertas dela. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tables_alert_rules_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este regra de alerta. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAlertRule"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAlertRule"];
                "multipart/form-data": components["schemas"]["PatchedAlertRule"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
        };
    };
    tables_columns_list: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
            };
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedColumnList"];
                };
            };
        };
    };
    tables_columns_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Column"];
                "application/x-www-form-urlencoded": components["schemas"]["Column"];
                "multipart/form-data": components["schemas"]["Column"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Column"];
                };
            };
        };
    };
    tables_columns_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este coluna. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Column"];
                };
            };
        };
    };
    tables_columns_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este coluna. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Column"];
                "application/x-www-form-urlencoded": components["schemas"]["Column"];
                "multipart/form-data": components["schemas"]["Column"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Column"];
                };
            };
        };
    };
    tables_columns_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este coluna. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tables_columns_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este coluna. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedColumn"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedColumn"];
                "multipart/form-data": components["schemas"]["PatchedColumn"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Column"];
                };
            };
        };
    };
    tables_columns_reorder_partial_update: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
            };
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedReorder"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedReorder"];
                "multipart/form-data": components["schemas"]["PatchedReorder"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedColumnList"];
                };
            };
        };
    };
    tables_records_list: {
        parameters: {
            query?: {
                due_after?: string;
                due_before?: string;
                has_due_date?: boolean;
                /** @description Campo de ordenação. Prefixo `-` inverte. Valores aceitos: `due_date`, `created_at`, `updated_at`, `position`. NULL sempre por último. Padrão: `due_date,created_at`, que já produz a ordem do RF11 — vencidos, hoje, próximos, futuros, sem vencimento. */
                ordering?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Filtra por status, separados por vírgula. Ex.: `overdue,due_today`. */
                status?: "due_soon" | "due_today" | "no_due" | "on_track" | "overdue";
            };
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecordList"];
                };
            };
        };
    };
    tables_records_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Record"];
                "application/x-www-form-urlencoded": components["schemas"]["Record"];
                "multipart/form-data": components["schemas"]["Record"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record"];
                };
            };
        };
    };
    tables_records_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este registro. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record"];
                };
            };
        };
    };
    tables_records_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este registro. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Record"];
                "application/x-www-form-urlencoded": components["schemas"]["Record"];
                "multipart/form-data": components["schemas"]["Record"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record"];
                };
            };
        };
    };
    tables_records_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este registro. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tables_records_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este registro. */
                id: string;
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRecord"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRecord"];
                "multipart/form-data": components["schemas"]["PatchedRecord"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record"];
                };
            };
        };
    };
    tables_records_export_retrieve: {
        parameters: {
            query?: {
                /** @description `,` (padrão) ou `;` — Excel em pt-BR costuma esperar `;`. */
                delimiter?: "," | ";";
            };
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
}
