# Generated by Django 5.2.17 on 2026-08-19 19:51

import django.core.validators
import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('alert_lead_days', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='dias de antecedência do alerta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'tabela',
                'verbose_name_plural': 'tabelas',
                'db_table': 'tables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(editable=False, max_length=64, verbose_name='chave')),
                ('name', models.CharField(max_length=80, verbose_name='rótulo')),
                ('type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('datetime', 'Data e hora'), ('boolean', 'Booleano'), ('email', 'E-mail'), ('select', 'Lista de opções'), ('due_date', 'Data de vencimento')], max_length=16, verbose_name='tipo')),
                ('position', models.PositiveSmallIntegerField(verbose_name='posição')),
                ('is_required', models.BooleanField(default=False, verbose_name='obrigatória')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='sensível')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='opções')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tables.table', verbose_name='tabela')),
            ],
            options={
                'verbose_name': 'coluna',
                'verbose_name_plural': 'colunas',
                'db_table': 'columns',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['user', '-created_at'], name='tables_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='tables_unique_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('alert_lead_days__lte', 365)), name='tables_alert_lead_days_range'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('table', 'key'), name='columns_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('table', 'position'), name='columns_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'due_date')), fields=('table',), name='columns_one_due_date_per_table'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['text', 'number', 'date', 'datetime', 'boolean', 'email', 'select', 'due_date'])), name='columns_type_valid'),
        ),
    ]
