# Generated by Django 5.2.17 on 2026-08-19 20:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0003_alter_record_table'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset_days', models.SmallIntegerField(help_text='3 = avisa 3 dias antes · 0 = no dia · -1 = 1 dia depois (cobrança de atraso).', validators=[django.core.validators.MinValueValidator(-365), django.core.validators.MaxValueValidator(365)], verbose_name='dias de antecedência')),
                ('channel', models.CharField(choices=[('in_app', 'No aplicativo'), ('email', 'E-mail')], default='in_app', max_length=16, verbose_name='canal')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tables.table', verbose_name='tabela')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'regra de alerta',
                'verbose_name_plural': 'regras de alerta',
                'db_table': 'alert_rules',
                'ordering': ['-offset_days'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_date', models.DateField(verbose_name='data de disparo')),
                ('due_date_snapshot', models.DateField(verbose_name='vencimento no disparo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('read', 'Lido'), ('dismissed', 'Descartado'), ('failed', 'Falhou')], default='pending', max_length=16, verbose_name='situação')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='notificado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lido em')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='records.record', verbose_name='registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.alertrule', verbose_name='regra')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'db_table': 'alerts',
                'ordering': ['-trigger_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(fields=('table', 'offset_days', 'channel'), name='alert_rules_unique'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.CheckConstraint(condition=models.Q(('offset_days__gte', -365), ('offset_days__lte', 365)), name='alert_rules_offset_range'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['in_app', 'email'])), name='alert_rules_channel_valid'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'status', '-trigger_date'], name='alerts_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['status', 'trigger_date'], name='alerts_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('record', 'rule', 'trigger_date'), name='alerts_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'sent', 'read', 'dismissed', 'failed'])), name='alerts_status_valid'),
        ),
    ]
