# Generated by Django 5.2.17 on 2026-08-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='delivery_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='tentativas de entrega'),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última tentativa'),
        ),
    ]
