# Generated by Django 5.2.17 on 2026-08-19 20:09

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='valores')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='vencimento')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='posição manual')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tables.table', verbose_name='tabela')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'db_table': 'records',
                'ordering': ['due_date', 'created_at'],
                'indexes': [models.Index(fields=['table', 'due_date'], name='records_table_due_idx'), models.Index(condition=models.Q(('due_date__isnull', False)), fields=['due_date'], name='records_due_scan_idx'), django.contrib.postgres.indexes.GinIndex(fields=['data'], name='records_data_gin', opclasses=['jsonb_path_ops'])],
            },
        ),
    ]
