# Generated by Django 5.2.17 on 2026-08-19 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_records_data_is_object'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='table',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tables.table', verbose_name='tabela'),
        ),
    ]
